export const categories = [
    "Self",
    "Lifestyle",
    "Anxiety",
    "Work",
    "Philosophy and arts",
    "Sex",
    "Relationships",
]

export const categoriesQuestion = {
    Work: [
        "In what ways are you tricky to work with (we all are)? What could you do to improve or resolve this?",
        "What would you like to say (but never yet said) to someone you've worked with?",
        "Who's the best boss you've ever had? What are traits that the perfect boss should have?",
        "What are your deepest professional goals?",
        "If we asked the childhood version of you what job they wanted to do, what would they say?",
        "Would you be happy to tell your friends how much you earn?",
        "How is your love of either team work or solo work reflected in your social life?",
        "Rank in order of importance in your career: money, status, creativity, social impact, colleagues?",
    ],
    Relationships: [
        "How might you be too romantic for your own good? Or not romantic enough?",
        "Complete this tought: When someone seems to be rejecting me, I...",
        "What did you learn about relationships from your parents?",
        "What kind of character traits are you drawn to in people that ,although compelling, can make for difficulties in relationships?",
        "In what ways have your parents influences your choice of partners?",
        "What do you and your partner argue about most?",
        "What are the best things you owe to your parents?",
        "What mistakes (of your parents or other people) you've observed that you not want to repeat with your own children?",
        "What haven't you been able to tell your/a partner?",
        "What you really look for in a friend is...",
        "Are you reluctant or open to bringing together people from different parts of your life?",
        "Is there anyone you regret losing touch with?",
        "Who do you want to impress in the family?",
        "The thing you'd like to be appreciated for are...",
    ],
    Anxiety: [
        "If you could wave a magic wand, what would you want to be able to alter about your life?",
        "What do you want to let go of, once and for all?",
        "What do you imagine people say when they gossip about you?",
        "What would you like to be reassured about?",
        "What did you learn about anxiety from each of your parents?",
        "What do you worry that others might think?",
        "Describe something you hate explaining to people and expect they should know about?",
        "What brings out the worst in you?",
        "Describe the family you were jealous of when you were a child",
        "What makes you most stressed?",
        "If you read your partners messages/emails what do you fear you might discover that would upset you?",
        "When you look in the mirror, what are you most afraid of seeing in yourself? (choose a literal or methaforical mirror to answer for)",
        "What can you not forgive someone for? ",
        "Who is the person you've treated the worst in love in the past?",
        "What are you ashamed of people knowing about you and money?",
        "What do people seldom properly understand about you?",
    ],
    Sex: [
        "In what ways do you disagree with your society's standard views on sex?",
        "What do you think people often don't get right in their attitudes to sex?",
        "What hang-ups do you have around sex?",
        "What thing about sex you find normal but most people would find strange?",
    ],
    Self: [
        "What would you like to tell your mother, if she could really listen?",
        "What would you like to tell your father, if he could really listen?",
        "Who do you need o impress?",
        "If you were a friend f yours, what would you tell yourself about the challanges you face?",
        "Around what features of your character does your self-hatred focus?",
        "What parts of your early life are you compensating for now?",
        "Are you where you wanted to be at this stage in your life? (From the perspective of before 5 years)",
        "What would yu ideally tell someone in your life? Reherse the speech now",
        "What sort of person do you admire and, secretly, envy too?",
        "Who was the first person to break your heart?",
        "How do you tend to react when someone betrays you?",
        "What are you ashamed of in yourself?",
        "How do you like to be comforted when you are sad?",
        "What was your favourite time when you were little? How did it make you feel?",
        "What are your biggest prejudices?",
    ],
    Lifestyle: [
        "Can you describe your taste in interiors or design?",
        "What makes a person a good travelling companion?",
        "Are you more attracted to a nomadic or settled life?",
        "What's the best evening you ever had?",
        "How can you change your life in line with something you have seen while traveling?",
        "What changes in some aspect of your lifestyle are you currently xontemplaiting or daydreaming about?",
    ],
    "Philosophy and arts": [
        "Have you ever had religious experience?",
        "Children notice a lot. If you were a child observing your life, what do you think you might say about it?",
        "What bit of your experience would you like to teach if all people at the planet would listen?",
        "Who in your life you will benefit from if you stopped seeing them as just a `monster"/"baddie`?",
        "What didn't you have the chance to finish before this moment? ",   
        "What would enable you to die (more/less) happy?",
        "How might the child in you be disappointed by your life as an adult?",
        "What's preventing you from working on your dreams?",
        "What have you never had the chance to tell someone and whom?",
        "If your heart was a house/building what would it be and what rooms/interiors would it have?",
        "If someone was writing a book with your biography which chapters would you ask them to skip?",
        "If you could reach out to your 7-8 year old self what words of comfort would you give?",
        "If you could reach out to your teenage self what advice would you give?",
        "If you were guaranteed an honest answe what would you ask and to whom?",
        "You are the absolute dictator of the world: what four things would you do?",
        "Without thinking too much, complete the sentence: The problem with most of the people I've been on a date with is...",
        "What are the main points you would like to be covered in a speech at your funeral?",
        "Imagine you were forsed to write a poem: what might be the first two lines?",
        "If you onlu knew you only had one year to live, how would you spend the next 12months?",
        "Would you prefer a view of a desert or of the sea and why?",
    ]
}